# Site Information
site_name: EE-Wiki
site_description: 愿你能在本站学习到你所需知识并为本站的发展贡献一份力 :)
site_author: EE-Wiki Team
strict: false

# Contents nav
nav:
  - 简介:
    - 关于我们: index.md
    - 参与建设: intro/join-us.md
  - 基础学科知识:
    - 模电:
      - 关于模电: basic-knowledge/analog-basic/index.md
    - 数电: 
      - 关于数电: basic-knowledge/digital-basic/index.md
    - C语言:
      - 关于C语言: basic-knowledge/c-lang/index.md
    - VerilogHDL:
      - 关于VerilogHDL: basic-knowledge/veriloghdl-lang/index.md
  - 行业入门软件:
    - Vivado: 
      - 关于Vivado: basic-software/vivado/index.md
    - Multisim:
      - 关于Multisim: basic-software/multisim/index.md
    # - Matlab:
    #   - 关于Matlab: basic-software/matlab/index.md

#Theme Settings
theme:
  name: material
  # 404 page
  static_templates:
    - 404.html
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: hack    
    code: hack
  favicon: assets/logo-black-48px.png
  logo: assets/logo-white-32px.png
  features:
     - navigation.top
     - navigation.tabs
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

# Repository Information
repo_name: 'EE-wiki/EE-wiki'
repo_url: 'https://github.com/EE-wiki/EE-wiki'

# Copyright
copyright: 'Copyright &copy; 2021 EE-Wiki Team'

# Extra Settings
extra:
  disqus: ee-wiki
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences